-- Generated by `just challenges-migration` (xtask challenges gen-migration) from
-- content/challenges/*.md. content/challenges/*.md is the source of truth (ADR-036) —
-- do not hand-edit challenge rows here; edit the source .md file and regenerate.

-- source: content/challenges/27-step-platform-deployment.md
INSERT INTO challenges (slug, title, job_id, description, short_description, tech_stack, category, url, image_url,
                     problem, constraints, decisions, implementation, outcomes, metrics,
                     related_job_slug, related_plan_module, related_adr, featured, sort_order, content_sha)
VALUES ('27-step-platform-deployment', '27-Step Platform Deployment Automation', (SELECT id FROM jobs WHERE slug = 'scala-computing'), 'Designed and implemented a 27-step automated deployment pipeline for a cloud-native
simulation platform (SaaS/PaaS). Covered infrastructure provisioning, service
deployment, database migrations, health checks, and rollback procedures across
multiple AWS accounts and regions.', 'End-to-end deployment automation for cloud simulation platform', 'Go,AWS CDK,AWS SSM,Step Functions,CodePipeline,Docker,ECS',
        'platform', NULL, NULL, 'End-to-end deployment automation for cloud simulation platform', 'Zero recurring cost, practical maintainability, and verifiable grounding.', 'Prioritize local-first MCP context and explicit plan/ADR alignment.', 'Designed and implemented a 27-step automated deployment pipeline for a cloud-native
simulation platform (SaaS/PaaS). Covered infrastructure provisioning, service
deployment, database migrations, health checks, and rollback procedures across
multiple AWS accounts and regions.',
        'End-to-end deployment automation for cloud simulation platform', 'See challenge description for measurable impact.', 'scala-computing', 'W-RAG', 'ADR-016', 1, 1, '24a3d6b00884fddc9ff658a18d9a9b49a33b2b53847ed447fb2c4cc11c2123f1')
ON CONFLICT(slug) DO UPDATE SET
    title = excluded.title,
    job_id = excluded.job_id,
    description = excluded.description,
    short_description = excluded.short_description,
    tech_stack = excluded.tech_stack,
    category = excluded.category,
    url = excluded.url,
    image_url = excluded.image_url,
    problem = excluded.problem,
    constraints = excluded.constraints,
    decisions = excluded.decisions,
    implementation = excluded.implementation,
    outcomes = excluded.outcomes,
    metrics = excluded.metrics,
    related_job_slug = excluded.related_job_slug,
    related_plan_module = excluded.related_plan_module,
    related_adr = excluded.related_adr,
    featured = excluded.featured,
    sort_order = excluded.sort_order,
    content_sha = excluded.content_sha;

-- source: content/challenges/deploy-baba-portfolio.md
INSERT INTO challenges (slug, title, job_id, description, short_description, tech_stack, category, url, image_url,
                     problem, constraints, decisions, implementation, outcomes, metrics,
                     related_job_slug, related_plan_module, related_adr, featured, sort_order, content_sha)
VALUES ('deploy-baba-portfolio', 'deploy-baba Portfolio Platform', (SELECT id FROM jobs WHERE slug = 'personal-projects'), 'Full-stack portfolio and resume platform built with Rust/Axum backend, React/Vite SPA,
SQLite on EFS, deployed to AWS Lambda at zero recurring cost. Features RAG-powered AI
Q&A, admin dashboard with CRUD, OpenAPI spec generation, and CI/CD via GitHub Actions.', 'Zero-cost Rust portfolio platform on AWS Lambda', 'Rust,Axum,React,Vite,TypeScript,SQLite,AWS Lambda,EFS,CloudFront,OpenTofu,Claude',
        'fullstack', 'https://github.com/shantopagla/deploy-baba', NULL, 'Zero-cost Rust portfolio platform on AWS Lambda', 'Zero recurring cost, practical maintainability, and verifiable grounding.', 'Prioritize local-first MCP context and explicit plan/ADR alignment.', 'Full-stack portfolio and resume platform built with Rust/Axum backend, React/Vite SPA,
SQLite on EFS, deployed to AWS Lambda at zero recurring cost. Features RAG-powered AI
Q&A, admin dashboard with CRUD, OpenAPI spec generation, and CI/CD via GitHub Actions.',
        'Zero-cost Rust portfolio platform on AWS Lambda', 'See challenge description for measurable impact.', 'personal-projects', 'W-RAG', 'ADR-016', 1, 0, 'ee4661bf96d7fdbfc632e3723040ad3817a84f3b90d04e1032c17e67bd60b96c')
ON CONFLICT(slug) DO UPDATE SET
    title = excluded.title,
    job_id = excluded.job_id,
    description = excluded.description,
    short_description = excluded.short_description,
    tech_stack = excluded.tech_stack,
    category = excluded.category,
    url = excluded.url,
    image_url = excluded.image_url,
    problem = excluded.problem,
    constraints = excluded.constraints,
    decisions = excluded.decisions,
    implementation = excluded.implementation,
    outcomes = excluded.outcomes,
    metrics = excluded.metrics,
    related_job_slug = excluded.related_job_slug,
    related_plan_module = excluded.related_plan_module,
    related_adr = excluded.related_adr,
    featured = excluded.featured,
    sort_order = excluded.sort_order,
    content_sha = excluded.content_sha;

-- source: content/challenges/rag-grounding-citation.md
INSERT INTO challenges (slug, title, job_id, description, short_description, tech_stack, category, url, image_url,
                     problem, constraints, decisions, implementation, outcomes, metrics,
                     related_job_slug, related_plan_module, related_adr, featured, sort_order, content_sha)
VALUES ('rag-grounding-citation', 'RAG Grounding & Citation Verification System', (SELECT id FROM jobs WHERE slug = 'personal-projects'), 'Designed and implemented an LLM output quality system for a portfolio AI assistant.
Built a grounding contract (ADR-016) that constrains Claude responses to verified
resume data via structured prompt assembly. The DefaultPromptAssembler injects live
portfolio chunks with citation tags, and entity_to_prose converters transform raw DB
rows into prose the LLM can ground against. HybridRetriever combines SQLite FTS5
full-text search with keyword-triggered live data injection, ensuring architecture and
auth questions surface code chunks instead of being crowded out by portfolio metadata.', 'LLM grounding contract with citation tags and hybrid retrieval', 'Rust,Claude API,SQLite FTS5,RAG,Prompt Engineering,Axum',
        'ai', NULL, NULL, 'LLM grounding contract with citation tags and hybrid retrieval', 'Zero recurring cost, practical maintainability, and verifiable grounding.', 'Prioritize local-first MCP context and explicit plan/ADR alignment.', 'Designed and implemented an LLM output quality system for a portfolio AI assistant.
Built a grounding contract (ADR-016) that constrains Claude responses to verified
resume data via structured prompt assembly. The DefaultPromptAssembler injects live
portfolio chunks with citation tags, and entity_to_prose converters transform raw DB
rows into prose the LLM can ground against. HybridRetriever combines SQLite FTS5
full-text search with keyword-triggered live data injection, ensuring architecture and
auth questions surface code chunks instead of being crowded out by portfolio metadata.',
        'LLM grounding contract with citation tags and hybrid retrieval', 'See challenge description for measurable impact.', 'personal-projects', 'W-RAG', 'ADR-016', 1, 3, '5f908e82f0e6af1eb48f3bf5193de2f44150e639bd08217c5fbe29d59494f214')
ON CONFLICT(slug) DO UPDATE SET
    title = excluded.title,
    job_id = excluded.job_id,
    description = excluded.description,
    short_description = excluded.short_description,
    tech_stack = excluded.tech_stack,
    category = excluded.category,
    url = excluded.url,
    image_url = excluded.image_url,
    problem = excluded.problem,
    constraints = excluded.constraints,
    decisions = excluded.decisions,
    implementation = excluded.implementation,
    outcomes = excluded.outcomes,
    metrics = excluded.metrics,
    related_job_slug = excluded.related_job_slug,
    related_plan_module = excluded.related_plan_module,
    related_adr = excluded.related_adr,
    featured = excluded.featured,
    sort_order = excluded.sort_order,
    content_sha = excluded.content_sha;

-- source: content/challenges/scala-multi-tenancy.md
INSERT INTO challenges (slug, title, job_id, description, short_description, tech_stack, category, url, image_url,
                     problem, constraints, decisions, implementation, outcomes, metrics,
                     related_job_slug, related_plan_module, related_adr, featured, sort_order, content_sha)
VALUES ('scala-multi-tenancy', 'Scala Multi-Tenancy Architecture', (SELECT id FROM jobs WHERE slug = 'scala-computing'), 'Architected a hierarchical multi-tenancy system for a SaaS simulation platform
supporting organization-level, team-level, and user-level resource isolation.
Implemented role-based access control, tenant-scoped data partitioning, and
cross-tenant sharing capabilities.', 'Hierarchical multi-tenant SaaS architecture with RBAC', 'Go,React,Redux,PostgreSQL,AWS,REST API',
        'fullstack', NULL, NULL, 'Hierarchical multi-tenant SaaS architecture with RBAC', 'Zero recurring cost, practical maintainability, and verifiable grounding.', 'Prioritize local-first MCP context and explicit plan/ADR alignment.', 'Architected a hierarchical multi-tenancy system for a SaaS simulation platform
supporting organization-level, team-level, and user-level resource isolation.
Implemented role-based access control, tenant-scoped data partitioning, and
cross-tenant sharing capabilities.',
        'Hierarchical multi-tenant SaaS architecture with RBAC', 'See challenge description for measurable impact.', 'scala-computing', 'W-RAG', 'ADR-016', 1, 2, 'ae0966275be2cfac7d72ceb2a71e34e0c42611840b7a58edfac6295116dd34a3')
ON CONFLICT(slug) DO UPDATE SET
    title = excluded.title,
    job_id = excluded.job_id,
    description = excluded.description,
    short_description = excluded.short_description,
    tech_stack = excluded.tech_stack,
    category = excluded.category,
    url = excluded.url,
    image_url = excluded.image_url,
    problem = excluded.problem,
    constraints = excluded.constraints,
    decisions = excluded.decisions,
    implementation = excluded.implementation,
    outcomes = excluded.outcomes,
    metrics = excluded.metrics,
    related_job_slug = excluded.related_job_slug,
    related_plan_module = excluded.related_plan_module,
    related_adr = excluded.related_adr,
    featured = excluded.featured,
    sort_order = excluded.sort_order,
    content_sha = excluded.content_sha;

